export const agentRowsJson = [
  {
    key: '1',
    agentName: 'Intelligent Document Processing',
    version: 'v2.3',
    category: 'Automation',
    specialization: 'Automated extraction, validation, and routing of mortgage documents',
    ownerName: 'Michael Carter',
    creationDate: '12 Jan 2026',
    lastUpdated: '28 Apr 2026',
    department: 'Mortgage Document Operations',
    status: 'Active',
    model: 'GPT-4.1 Mini',
    dataSources: 'Mortgage applications, KYC docs, income statements',
    responseSla: '6 sec average',
    region: 'Sweden Central',
    contactEmail: 'michael.carter@slideaihub.com',
    contactPhone: '+46 8 5550 1201',
    description:
      'Processes incoming mortgage documents, extracts critical fields, flags missing items, and routes each case to the correct underwriting workflow.',
  },
  {
    key: '2',
    agentName: 'Policy Insight Copilot',
    version: 'v1.8',
    category: 'Knowledge Search',
    specialization: 'Policy clause lookup and contextual summarization',
    ownerName: 'Emily Johnson',
    creationDate: '21 Dec 2025',
    lastUpdated: '30 Apr 2026',
    department: 'Underwriting Knowledge Office',
    status: 'Pilot',
    model: 'GPT-4.1',
    dataSources: 'Policy library, endorsement notes',
    responseSla: '9 sec average',
    region: 'Sweden Central',
    contactEmail: 'emily.johnson@slideaihub.com',
    contactPhone: '+46 8 5550 1202',
    description:
      'Surfaces policy language, compares endorsements, and prepares quick clause summaries for support and underwriting teams.',
  },
  {
    key: '3',
    agentName: 'Fraud Signal Analyst',
    version: 'v3.1',
    category: 'Analytics',
    specialization: 'Anomaly spotting from historical claims patterns',
    ownerName: 'Daniel Brooks',
    creationDate: '08 Feb 2026',
    lastUpdated: '01 May 2026',
    department: 'Risk Intelligence',
    status: 'Monitored',
    model: 'GPT-4.1 Mini',
    dataSources: 'Claims history, investigation flags',
    responseSla: '11 sec average',
    region: 'Sweden Central',
    contactEmail: 'daniel.brooks@slideaihub.com',
    contactPhone: '+46 8 5550 1203',
    description:
      'Highlights suspicious clusters, explains risk signals, and supports reviewers with a compact fraud-risk snapshot.',
  },
  {
    key: '4',
    agentName: 'Regulation Guard',
    version: 'v2.0',
    category: 'Compliance',
    specialization: 'Jurisdiction checks and rule adherence hints',
    ownerName: 'Olivia Bennett',
    creationDate: '17 Nov 2025',
    lastUpdated: '29 Apr 2026',
    department: 'Compliance Governance',
    status: 'Active',
    model: 'GPT-4.1',
    dataSources: 'Regulatory memos, controls register',
    responseSla: '7 sec average',
    region: 'Sweden Central',
    contactEmail: 'olivia.bennett@slideaihub.com',
    contactPhone: '+46 8 5550 1204',
    description:
      'Checks workflows against policy controls and jurisdiction rules, then flags gaps before a case is finalized.',
  },
  {
    key: '5',
    agentName: 'Broker Communicator',
    version: 'v1.6',
    category: 'Communication',
    specialization: 'Client-ready draft emails and follow-up prompts',
    ownerName: 'Sophia Turner',
    creationDate: '02 Mar 2026',
    lastUpdated: '03 May 2026',
    department: 'Broker Relations',
    status: 'Ready',
    model: 'GPT-4.1 Mini',
    dataSources: 'CRM notes, email templates',
    responseSla: '5 sec average',
    region: 'Sweden Central',
    contactEmail: 'sophia.turner@slideaihub.com',
    contactPhone: '+46 8 5550 1205',
    description:
      'Drafts broker updates, follow-up nudges, and summary responses using approved tone and communication guardrails.',
  },
  {
    key: '6',
    agentName: 'Data Quality Sentinel',
    version: 'v2.7',
    category: 'Quality Assurance',
    specialization: 'Missing-field detection and consistency checks',
    ownerName: 'Jackson Reed',
    creationDate: '14 Jan 2026',
    lastUpdated: '27 Apr 2026',
    department: 'Data Stewardship',
    status: 'Active',
    model: 'GPT-4.1 Mini',
    dataSources: 'Submission forms, validation rules',
    responseSla: '4 sec average',
    region: 'Sweden Central',
    contactEmail: 'jackson.reed@slideaihub.com',
    contactPhone: '+46 8 5550 1206',
    description:
      'Validates structured inputs, catches missing or conflicting values, and recommends corrections before submission.',
  },
];
