import '../App.css';

export const loginClassNames = {
  screen: 'login-screen',
  card: 'login-card',
  brandSection: 'brand-section',
  brandLogo: 'brand-logo',
  brandTitle: 'brand-title',
  brandSubtitle: 'brand-subtitle',
  formHelperRow: 'form-helper-row',
  forgotLink: 'forgot-link',
  loginButton: 'login-button',
  forgotCopy: 'forgot-copy',
  forgotActions: 'forgot-actions',
};

export const layoutClassNames = {
  layout: 'dashboard-layout',
  header: 'dashboard-header',
  brandMini: 'brand-mini',
  brandMark: 'brand-mark',
  brandMarkIcon: 'brand-mark-icon',
  brandMarkImage: 'brand-mark-image',
  brandCopy: 'brand-copy',
  miniLogo: 'mini-logo',
  headerRight: 'header-right',
  headerLogo: 'header-logo',
  headerWordmark: 'header-wordmark',
  headerTitle: 'header-title',
  headerSubtitle: 'header-subtitle',
  headerActions: 'header-actions',
  headerUtility: 'header-utility',
  headerLogoutButton: 'header-logout-button',
  headerProfile: 'header-profile',
  headerProfileItem: 'header-profile-item',
  headerProfileIcon: 'header-profile-icon',
  headerProfileText: 'header-profile-text',
  headerProfileLabel: 'header-profile-label',
  headerProfileValue: 'header-profile-value',
  content: 'dashboard-content',
  welcomeCard: 'welcome-card',
  userAvatar: 'user-avatar',
  welcomeCaption: 'welcome-caption',
  welcomeName: 'welcome-name',
};
 

export const tableClassNames = {
  card: 'table-card',
  table: 'agent-table',
  searchInput: 'agent-search-input',
  searchInputIcon: 'agent-search-input-icon',
  agentList: 'agent-list',
  agentCard: 'agent-card',
  agentCardHeader: 'agent-card-header',
  agentCardIdentity: 'agent-card-identity',
  agentCardCopy: 'agent-card-copy',
  agentCardTitleRow: 'agent-card-title-row',
  agentCardContact: 'agent-card-contact',
  agentCardContactDivider: 'agent-card-contact-divider',
  agentCardBadges: 'agent-card-badges',
  agentVersionTag: 'agent-version-tag',
  agentVersionInlineTag: 'agent-version-inline-tag',
  agentRatingPill: 'agent-rating-pill',
  agentRatingStars: 'agent-rating-stars',
  agentRatingValue: 'agent-rating-value',
  agentDateTag: 'agent-date-tag',
  agentCardDescriptionSection: 'agent-card-description-section',
  agentCardDescriptionHeader: 'agent-card-description-header',
  agentCardDescriptionHeadingWrap: 'agent-card-description-heading-wrap',
  agentCardDescriptionLabel: 'agent-card-description-label',
  agentDepartmentTag: 'agent-department-tag',
  agentCardDescription: 'agent-card-description',
  agentInfoButton: 'agent-info-button',
  agentAvatar: 'agent-avatar',
  agentNameButton: 'agent-name-button',
  agentNameText: 'agent-name-text',
  categoryTag: 'category-tag',
  categoryIcon: 'category-icon',
  metricsViewButton: 'metrics-view-button',
  registerButton: 'register-button',
  agentRowActive: 'agent-row-active',
  agentDetailPanel: 'agent-detail-panel',
  agentDetailHeader: 'agent-detail-header',
  agentDetailEyebrow: 'agent-detail-eyebrow',
  agentDetailTitle: 'agent-detail-title',
  agentDetailMeta: 'agent-detail-meta',
  agentDetailCategoryTag: 'agent-detail-category-tag',
  agentDetailMetaText: 'agent-detail-meta-text',
  agentDetailCopy: 'agent-detail-copy',
  agentDetailGrid: 'agent-detail-grid',
  agentDetailItem: 'agent-detail-item',
  agentDetailItemLabel: 'agent-detail-item-label',
  agentDetailItemValue: 'agent-detail-item-value',
  agentDetailContactWrap: 'agent-detail-contact-wrap',
  agentDetailLink: 'agent-detail-link',
};

export const agentPageClassNames = {
  layout: 'agent-page-layout',
  content: 'agent-page-content',
  card: 'agent-page-card',
  title: 'agent-page-title',
  copy: 'agent-page-copy',
  meta: 'agent-page-meta',
  liveSection: 'agent-page-live-section',
  loaderWrap: 'agent-page-loader-wrap',
  loaderOrb: 'agent-page-loader-orb',
  loaderText: 'agent-page-loader-text',
  responseLabel: 'agent-page-response-label',
  responseCard: 'agent-page-response-card',
  responsePre: 'agent-page-response-pre',
  errorText: 'agent-page-error-text',
  actions: 'agent-page-actions',
};

export const createLoginBackgroundStyle = (backgroundImage) => ({
  backgroundImage: `linear-gradient(130deg, rgba(72, 52, 153, 0.58), rgba(31, 41, 55, 0.46)), url(${backgroundImage})`,
});
